<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>TRACE;DEBUG;JETBRAINS_ANNOTATIONS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Runtime\Invocation\Operations\**" />
    <EmbeddedResource Remove="Runtime\Invocation\Operations\**" />
    <None Remove="Runtime\Invocation\Operations\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AsyncUtilities" />
    <PackageReference Include="Ben.Demystifier" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="NetFabric.Hyperlinq" />
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="Polly" />
  </ItemGroup>
</Project>