// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:DragonSpark.Model.None.op_Equality(DragonSpark.Model.None,DragonSpark.Model.None)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:DragonSpark.Model.None.op_Inequality(DragonSpark.Model.None,DragonSpark.Model.None)~System.Boolean")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DragonSpark.Compose.Extents.Commands.CommandExtent.Type``1~DragonSpark.Compose.Extents.Commands.CommandExtent{``0}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DragonSpark.Compose.Extents.Conditions.ConditionExtent.Type``1~DragonSpark.Compose.Extents.Conditions.ConditionExtent{``0}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DragonSpark.Compose.Extents.Extent.Type``1~DragonSpark.Compose.Extents.Extent{``0}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DragonSpark.Compose.Extents.Results.ResultExtent.Type``1~DragonSpark.Compose.Extents.Results.ResultExtent{``0}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DragonSpark.Compose.Extents.Selections.SelectionExtent.Type``1~DragonSpark.Compose.Extents.Selections.SelectionExtent{``0}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DragonSpark.Compose.ModelContext.Generic(System.Type)~DragonSpark.Compose.Extents.Generics.GenericContext")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Commands.CommandExtent.Any")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Commands.CommandExtent.None")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Commands.CommandExtent.System")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Commands.CommandExtent.SystemExtents.Metadata")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Commands.CommandExtent.SystemExtents.Type")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Conditions.ConditionExtent.Any")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Conditions.ConditionExtent.None")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Conditions.ConditionExtent.System")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Conditions.ConditionExtent.SystemExtents.Metadata")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Conditions.ConditionExtent.SystemExtents.Type")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Extent.Any")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Extent.None")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Extent.System")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Results.ResultExtent.Any")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Results.ResultExtent.None")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Results.ResultExtent.System")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Results.ResultExtent.SystemExtents.Metadata")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Results.ResultExtent.SystemExtents.Type")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Selections.SelectionExtent.Any")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Selections.SelectionExtent.None")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Selections.SelectionExtent.System")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Selections.SelectionExtent.SystemExtents.Metadata")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.Extents.Selections.SelectionExtent.SystemExtents.Type")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.ModelContext.Command")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.ModelContext.Condition")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.ModelContext.Result")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DragonSpark.Compose.ModelContext.Selection")]
