//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonSpark.Properties {
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DragonSpark.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Message_AnErrorHasOccuredWhileConsumingThisService {
            get {
                return ResourceManager.GetString("Message_AnErrorHasOccuredWhileConsumingThisService", resourceCulture);
            }
        }
        
        internal static string Message_CheckingAccess {
            get {
                return ResourceManager.GetString("Message_CheckingAccess", resourceCulture);
            }
        }
        
        internal static string Message_DefaultResourceManager {
            get {
                return ResourceManager.GetString("Message_DefaultResourceManager", resourceCulture);
            }
        }
        
        internal static string Message_InitializingInterface {
            get {
                return ResourceManager.GetString("Message_InitializingInterface", resourceCulture);
            }
        }
        
        internal static string Message_Loading {
            get {
                return ResourceManager.GetString("Message_Loading", resourceCulture);
            }
        }
        
        internal static string Message_LoadingPolicyForResource {
            get {
                return ResourceManager.GetString("Message_LoadingPolicyForResource", resourceCulture);
            }
        }
        
        internal static string Message_Logging_DirectoryInfo {
            get {
                return ResourceManager.GetString("Message_Logging_DirectoryInfo", resourceCulture);
            }
        }
        
        internal static string Message_NoBusyIndicatorFound {
            get {
                return ResourceManager.GetString("Message_NoBusyIndicatorFound", resourceCulture);
            }
        }
        
        internal static string Message_Null {
            get {
                return ResourceManager.GetString("Message_Null", resourceCulture);
            }
        }
        
        internal static string Message_NullOrEmpty {
            get {
                return ResourceManager.GetString("Message_NullOrEmpty", resourceCulture);
            }
        }
        
        internal static string Message_PropertyNotFound {
            get {
                return ResourceManager.GetString("Message_PropertyNotFound", resourceCulture);
            }
        }
        
        internal static string Message_SynchronizationContext_LoggingMessage {
            get {
                return ResourceManager.GetString("Message_SynchronizationContext_LoggingMessage", resourceCulture);
            }
        }
        
        internal static string Message_Workspace_Created {
            get {
                return ResourceManager.GetString("Message_Workspace_Created", resourceCulture);
            }
        }
        
        internal static string Message_Workspace_Dispose {
            get {
                return ResourceManager.GetString("Message_Workspace_Dispose", resourceCulture);
            }
        }
    }
}
