//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonSpark.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DragonSpark.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while consuming this service. Please contact your administrator for more information. Error ID: {handlingInstanceID}.
        /// </summary>
        internal static string Message_AnErrorHasOccuredWhileConsumingThisService {
            get {
                return ResourceManager.GetString("Message_AnErrorHasOccuredWhileConsumingThisService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking access on Resource:{0}, Action:{1} for Principal:{2}.
        /// </summary>
        internal static string Message_CheckingAccess {
            get {
                return ResourceManager.GetString("Message_CheckingAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource {0} not found in {1}..
        /// </summary>
        internal static string Message_DefaultResourceManager {
            get {
                return ResourceManager.GetString("Message_DefaultResourceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Interface....
        /// </summary>
        internal static string Message_InitializingInterface {
            get {
                return ResourceManager.GetString("Message_InitializingInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Message_Loading {
            get {
                return ResourceManager.GetString("Message_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading policy for Resource:{0}, Action:{1}.
        /// </summary>
        internal static string Message_LoadingPolicyForResource {
            get {
                return ResourceManager.GetString("Message_LoadingPolicyForResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were problems while copying the directory &apos;{0}&apos;.  The encountered problems are as follows:{1}{2}.
        /// </summary>
        internal static string Message_Logging_DirectoryInfo {
            get {
                return ResourceManager.GetString("Message_Logging_DirectoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No busy indicator with name &apos;{0}&apos; was found in the UI hierarchy. Using modal..
        /// </summary>
        internal static string Message_NoBusyIndicatorFound {
            get {
                return ResourceManager.GetString("Message_NoBusyIndicatorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is null..
        /// </summary>
        internal static string Message_Null {
            get {
                return ResourceManager.GetString("Message_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified argument is null or empty..
        /// </summary>
        internal static string Message_NullOrEmpty {
            get {
                return ResourceManager.GetString("Message_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A property that&apos;s part of a key was not found..
        /// </summary>
        internal static string Message_PropertyNotFound {
            get {
                return ResourceManager.GetString("Message_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured while setting the property &apos;{0}&apos; of object type &apos;{1}&apos; to a value of type &apos;{2}&apos; with value &apos;{3}&apos;: {4}..
        /// </summary>
        internal static string Message_SynchronizationContext_LoggingMessage {
            get {
                return ResourceManager.GetString("Message_SynchronizationContext_LoggingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Directory: {0}..
        /// </summary>
        internal static string Message_Workspace_Created {
            get {
                return ResourceManager.GetString("Message_Workspace_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Directory: {0}..
        /// </summary>
        internal static string Message_Workspace_Dispose {
            get {
                return ResourceManager.GetString("Message_Workspace_Dispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0:FileName}]
        ///Format={0:Delimiter}
        ///ColNameHeader={0:FirstRowContainsHeaderInfo}
        ///CharacterSet={0:CharacterSet}.
        /// </summary>
        internal static string SchemaTemplate {
            get {
                return ResourceManager.GetString("SchemaTemplate", resourceCulture);
            }
        }
    }
}
